// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Models.Bairro", b =>
                {
                    b.Property<int>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBairro"), 1L, 1);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CEP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("IdBairro")
                        .HasName("PK__Bairro__4F198E84DDE68F66");

                    b.ToTable("Bairro", (string)null);
                });

            modelBuilder.Entity("API.Models.BairroTransportadora", b =>
                {
                    b.Property<int>("IdBairroTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBairroTransportadora"), 1L, 1);

                    b.Property<int?>("IdBairro")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransportadora")
                        .HasColumnType("int");

                    b.HasKey("IdBairroTransportadora")
                        .HasName("PK__BairroTr__239077AE985D2E7F");

                    b.HasIndex("IdBairro");

                    b.HasIndex("IdTransportadora");

                    b.ToTable("BairroTransportadora", (string)null);
                });

            modelBuilder.Entity("API.Models.Informacao", b =>
                {
                    b.Property<int>("IdInformacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInformacao"), 1L, 1);

                    b.Property<DateTime?>("Aniversario")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NumeroContato")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdInformacao")
                        .HasName("PK__Informac__40403D5976A461AE");

                    b.ToTable("Informacao", (string)null);
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.Property<int>("IdTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransportadora"), 1L, 1);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNPJ");

                    b.Property<int?>("IdInformacao")
                        .HasColumnType("int");

                    b.Property<int?>("MediaPreco")
                        .HasColumnType("int");

                    b.Property<int?>("NotaMediaQualidade")
                        .HasColumnType("int");

                    b.HasKey("IdTransportadora")
                        .HasName("PK__Transpor__477CF3FC1971B51E");

                    b.HasIndex("IdInformacao");

                    b.ToTable("Transportadora", (string)null);
                });

            modelBuilder.Entity("API.Models.BairroTransportadora", b =>
                {
                    b.HasOne("API.Models.Bairro", "IdBairroNavigation")
                        .WithMany("BairroTransportadoras")
                        .HasForeignKey("IdBairro")
                        .HasConstraintName("FK__BairroTra__IdBai__2B3F6F97");

                    b.HasOne("API.Models.Transportadora", "IdTransportadoraNavigation")
                        .WithMany("BairroTransportadoras")
                        .HasForeignKey("IdTransportadora")
                        .HasConstraintName("FK__BairroTra__IdTra__2C3393D0");

                    b.Navigation("IdBairroNavigation");

                    b.Navigation("IdTransportadoraNavigation");
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.HasOne("API.Models.Informacao", "IdInformacaoNavigation")
                        .WithMany("Transportadoras")
                        .HasForeignKey("IdInformacao")
                        .HasConstraintName("FK__Transport__IdInf__286302EC");

                    b.Navigation("IdInformacaoNavigation");
                });

            modelBuilder.Entity("API.Models.Bairro", b =>
                {
                    b.Navigation("BairroTransportadoras");
                });

            modelBuilder.Entity("API.Models.Informacao", b =>
                {
                    b.Navigation("Transportadoras");
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.Navigation("BairroTransportadoras");
                });
#pragma warning restore 612, 618
        }
    }
}
