// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<int?>("IdInformacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoja")
                        .HasColumnType("int");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D59466425C5DBBCC");

                    b.HasIndex("IdInformacao");

                    b.HasIndex("IdLoja");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("API.Models.Informacao", b =>
                {
                    b.Property<int>("IdInformacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInformacao"), 1L, 1);

                    b.Property<DateTime?>("Aniversario")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NumeroContato")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdInformacao")
                        .HasName("PK__Informac__40403D5962470CF0");

                    b.ToTable("Informacao", (string)null);
                });

            modelBuilder.Entity("API.Models.Loja", b =>
                {
                    b.Property<int>("IdLoja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoja"), 1L, 1);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNPJ");

                    b.Property<int?>("IdInformacao")
                        .HasColumnType("int");

                    b.HasKey("IdLoja")
                        .HasName("PK__Loja__38C45D6491E1114D");

                    b.HasIndex("IdInformacao");

                    b.ToTable("Loja", (string)null);
                });

            modelBuilder.Entity("API.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"), 1L, 1);

                    b.Property<string>("Detalhes")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransportadora")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedido__9D335DC322938805");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTransportadora");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("API.Models.RegiaoTransportadora", b =>
                {
                    b.Property<int>("IdRegiaoTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegiaoTransportadora"), 1L, 1);

                    b.Property<int>("IdRegiao")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransportadora")
                        .HasColumnType("int");

                    b.HasKey("IdRegiaoTransportadora")
                        .HasName("PK__RegiaoTr__E1AB131CB96DA58E");

                    b.HasIndex("IdTransportadora");

                    b.ToTable("RegiaoTransportadora", (string)null);
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.Property<int>("IdTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransportadora"), 1L, 1);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNPJ");

                    b.Property<int?>("IdInformacao")
                        .HasColumnType("int");

                    b.Property<int?>("MediaPreco")
                        .HasColumnType("int");

                    b.Property<int?>("NotaMediaQualidade")
                        .HasColumnType("int");

                    b.HasKey("IdTransportadora")
                        .HasName("PK__Transpor__477CF3FCE932F2D8");

                    b.HasIndex("IdInformacao");

                    b.ToTable("Transportadora", (string)null);
                });

            modelBuilder.Entity("API.Models.TransportadoraTipoEncomendum", b =>
                {
                    b.Property<int>("IdTransportadoraTipoEncomenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransportadoraTipoEncomenda"), 1L, 1);

                    b.Property<int?>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransportadora")
                        .HasColumnType("int");

                    b.HasKey("IdTransportadoraTipoEncomenda")
                        .HasName("PK__Transpor__657B1FCE79CFFF99");

                    b.HasIndex("IdTransportadora");

                    b.ToTable("TransportadoraTipoEncomenda");
                });

            modelBuilder.Entity("API.Models.Cliente", b =>
                {
                    b.HasOne("API.Models.Informacao", "IdInformacaoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdInformacao")
                        .HasConstraintName("FK__Cliente__IdInfor__36B12243");

                    b.HasOne("API.Models.Loja", "IdLojaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdLoja")
                        .HasConstraintName("FK__Cliente__IdLoja__37A5467C");

                    b.Navigation("IdInformacaoNavigation");

                    b.Navigation("IdLojaNavigation");
                });

            modelBuilder.Entity("API.Models.Loja", b =>
                {
                    b.HasOne("API.Models.Informacao", "IdInformacaoNavigation")
                        .WithMany("Lojas")
                        .HasForeignKey("IdInformacao")
                        .HasConstraintName("FK__Loja__IdInformac__33D4B598");

                    b.Navigation("IdInformacaoNavigation");
                });

            modelBuilder.Entity("API.Models.Pedido", b =>
                {
                    b.HasOne("API.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Pedido__IdClient__3B75D760");

                    b.HasOne("API.Models.Transportadora", "IdTransportadoraNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdTransportadora")
                        .HasConstraintName("FK__Pedido__IdTransp__3A81B327");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdTransportadoraNavigation");
                });

            modelBuilder.Entity("API.Models.RegiaoTransportadora", b =>
                {
                    b.HasOne("API.Models.Transportadora", "IdTransportadoraNavigation")
                        .WithMany("RegiaoTransportadoras")
                        .HasForeignKey("IdTransportadora")
                        .HasConstraintName("FK__RegiaoTra__IdTra__29572725");

                    b.Navigation("IdTransportadoraNavigation");
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.HasOne("API.Models.Informacao", "IdInformacaoNavigation")
                        .WithMany("Transportadoras")
                        .HasForeignKey("IdInformacao")
                        .HasConstraintName("FK__Transport__IdInf__267ABA7A");

                    b.Navigation("IdInformacaoNavigation");
                });

            modelBuilder.Entity("API.Models.TransportadoraTipoEncomendum", b =>
                {
                    b.HasOne("API.Models.Transportadora", "IdTransportadoraNavigation")
                        .WithMany("TransportadoraTipoEncomenda")
                        .HasForeignKey("IdTransportadora")
                        .HasConstraintName("FK__Transport__IdTra__3E52440B");

                    b.Navigation("IdTransportadoraNavigation");
                });

            modelBuilder.Entity("API.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("API.Models.Informacao", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Lojas");

                    b.Navigation("Transportadoras");
                });

            modelBuilder.Entity("API.Models.Loja", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("API.Models.Transportadora", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("RegiaoTransportadoras");

                    b.Navigation("TransportadoraTipoEncomenda");
                });
#pragma warning restore 612, 618
        }
    }
}
